admin:
  existingSecret: grafana-secrets
service:
  type: NodePort
  nodePort: 31900
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc.cluster.local
      access: proxy
      isDefault: true
dashboards:
  default:
    prometheus-stats:
      # Ref: https://grafana.com/dashboards/10000
      gnetId: 10000
      revision: 1
      datasource: Prometheus
    kube-eagle-stats:
      # Ref: https://grafana.com/dashboards/9871
      gnetId: 9871
      revision: 2
      datasource: Prometheus
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "selfsigned-issuer"
  hosts:
    - "dashboard.{{nginx_ingress.master_public_ip }}.xip.io"
  tls:
          - hosts:
                        - "dashboard.{{nginx_ingress.master_public_ip }}.xip.io"
                        secretName: grafana-selfsigned

dciangot at DESKTOP-Q7M5QBM in ~/private/ingress_test 
$ vim values_grafana.yaml

dciangot at DESKTOP-Q7M5QBM in ~/private/ingress_test 
$ cat values_grafana.yaml
admin:
  existingSecret: grafana-secrets
service:
  type: NodePort
  nodePort: 31900
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc.cluster.local
      access: proxy
      isDefault: true
dashboards:
  default:
    prometheus-stats:
      # Ref: https://grafana.com/dashboards/10000
      gnetId: 10000
      revision: 1
      datasource: Prometheus
    kube-eagle-stats:
      # Ref: https://grafana.com/dashboards/9871
      gnetId: 9871
      revision: 2
      datasource: Prometheus
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "selfsigned-issuer"
  hosts:
    - "grafana.{{nginx_ingress.master_public_ip }}.xip.io"
  tls:
    - hosts:
      - "grafana.{{nginx_ingress.master_public_ip }}.xip.io"
      secretName: grafana-selfsigned